FROM python:3.12-slim

# 1. Базовые зависимости + docker-cli
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    git \
    jq \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

# 2. Trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
    | sh -s -- -b /usr/local/bin

# 3. Node LTS + npx (для cdxgen)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update && apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

# Для linux-контейнера на Apple Silicon убираем прямой бинарник CycloneDX CLI
# 4. CycloneDX CLI
# RUN curl -L https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 \
#     -o /usr/local/bin/cyclonedx && \
#     chmod +x /usr/local/bin/cyclonedx

WORKDIR /app
COPY . /app

WORKDIR /app/script
RUN python -m pip install --upgrade pip && \
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

WORKDIR /app/secgensbom
RUN chmod +x *.sh

ENV REPO_ROOT=/app \
    PROJECT_DIR=/app/script \
    IMAGE_NAME=sbom-formatter:inside \
    OUTPUT_DIR=/app/secgensbom_out \
    SBOM_DIR=/app/sbom \
    REPORTS_DIR=/app/reports

WORKDIR /app
ENTRYPOINT ["/bin/bash"]